### ISSUE TITLE
Ransomeware error

### ISSUE THREAD

**Issue by tflsaga** [DamagingRose/Rose-Grabber#127]
arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'

Also does not grab anything

**Comment by gumbobr0t** [comment]
yuh i finished my own ransomware yesterday, another old dev did shit, i will try mine when im home and when it works fine i implement it in rose

and ur sure that u enabled stuff on the functions tab? i need more information on what features you enabled (if u did so), it could also be a vm, or the victim js doesn't have any saved data?

**Comment by gumbobr0t** [comment]
@tflsaga

**Comment by tflsaga** [comment]
The things enabled were uac, startup, screenshot, btc miner (does not work) and ransomware. I inputted all required info for ransomware. If you're updating to a new one tmrw then it's fine, thank you.
@gumbobr0t

**Comment by tflsaga** [comment]
Also the victim was on his main pc. Rose hasn't been able to grab anything either which is weird (probably a me issue I just get errors) but I'm just trying to get the ransomware to work.

**Comment by gumbobr0t** [comment]
buddy maybe because you did not enable to steal tokens, browser, ip, wifi, device & more, there is also in the functions tab a row to do that

**Comment by gumbobr0t** [comment]
only things that do not work are obfuscation, miner, ransomware & spread malware


ransomware will be fixed in the next days, same for spread malware,

dont forget to enable stealer options 😭

**Comment by tflsaga** [comment]
Ok thank you, didn't know I needed stealer for other features to work. I was just trying to reduce file size.

**Comment by gumbobr0t** [comment]
yuh at the top in the builder you need to go to the functions tab & enable the features you want, ofc put your webhook & a build name at the home menu in tho
