### ISSUE TITLE
Rose ransomware issues all errors

### ISSUE THREAD

**Issue by tflsaga** [DamagingRose/Rose-Grabber#128]
Rose ransomware not working. All features enabled except for file spoofer, use SCR for startup, external RATs and pump file. 
Errors:
 arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'
Other unrelated errors: 
[Errno 2] No such file or directory: 'C:\\Users\\TEMP\\AppData\\Roaming\\ROSE_ON_TOP\\wifi-stealer_DrtSsfW6JLYTaqYvbvwaCnbD7.txt'

**Comment by gumbobr0t** [comment]
yuh dropping update today with new ransomware & roseguardian (obfuscator), the current ransomware is shit and contains some bugs
