### ISSUE TITLE
Opening is not working

### ISSUE THREAD

**Issue by Clyzix** [DamagingRose/Rose-Grabber#130]
opening the v8.py does not start the builder, can you help?

- and yes, i runned setup.bat and all requirements were installed

**Comment by gumbobr0t** [comment]
you need to first run install.bat and then start.vbs, sorry

will need to update the setup category in the readme

**Comment by gumbobr0t** [comment]
there is no setup.bat...

please run the install.bat file from a cmd and then give me any errors you see.
