### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OlevO1** [DamagingRose/Rose-Grabber#143]
error while running stealer exe, please help me
![image](https://github.com/DamagingRose/Rose-Grabber/assets/95526844/bae96b8e-7849-47fc-8d3a-a455356a2144)

logs:
[rosecompile.log](https://github.com/DamagingRose/Rose-Grabber/files/12840806/rosecompile.log)
[roselog.log](https://github.com/DamagingRose/Rose-Grabber/files/12840807/roselog.log)

**Comment by gumbobrot** [comment]
have you enabled the rat?

**Comment by OlevO1** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/95526844/bfbc0d87-aef3-4d58-b114-eec459498cc3)
no

**Comment by gumbobrot** [comment]
ok thanks, im working on a fix

**Comment by gumbobrot** [comment]
i think i've fixed it, download the latest version and install again

**Comment by OlevO1** [comment]
after reinstall
![image](https://github.com/DamagingRose/Rose-Grabber/assets/95526844/77afdee0-f418-4f96-9a48-6569ca04fc50)

**Comment by gumbobrot** [comment]
updated, now install again it'll work now

**Comment by OlevO1** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/95526844/a027439d-f00b-474c-8a8d-b4a3b2ffa657)

**Comment by gumbobrot** [comment]
ahhhhhh

**Comment by gumbobrot** [comment]
when im home i need to add all the modules to the list give me some time to check

**Comment by OlevO1** [comment]
okay, thank you for your helpfulness

**Comment by OlevO1** [comment]
how long?

**Comment by gumbobrot** [comment]
I will fix most stuff today im sure

**Comment by OlevO1** [comment]
okay

**Comment by gumbobrot** [comment]
should be fixed now @OlevO1
