### ISSUE TITLE
invalid escape sequence (install.bat 29/30?)

### ISSUE THREAD

**Issue by Fenius64** [DamagingRose/Rose-Grabber#144]
so basically idk why it happened but i installed python 12, opened install.bat, and then it exits out with an invalid escape sequence error :/

**Comment by gumbobrot** [comment]
python 12? could you attack an image and provide your exact python vers, also make sure you have added it to path

**Comment by Fenius64** [comment]
this is what i get when i type python -v

import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\__pycache__\__init__.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\__init__.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\__pycache__\\__init__.cpython-312.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <class '_frozen_importlib.FrozenImporter'>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\__pycache__\aliases.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\aliases.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\__pycache__\\aliases.cpython-312.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA118980>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA0EADB0>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\__pycache__\utf_8.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\utf_8.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\__pycache__\\utf_8.cpython-312.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA11B1D0>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\__pycache__\cp1252.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\__pycache__\\cp1252.cpython-312.pyc'
import 'encodings.cp1252' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA11B380>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <class '_frozen_importlib.FrozenImporter'>
import 'io' # <class '_frozen_importlib.FrozenImporter'>
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <class '_frozen_importlib.FrozenImporter'>
import '_collections_abc' # <class '_frozen_importlib.FrozenImporter'>
import 'genericpath' # <class '_frozen_importlib.FrozenImporter'>
import '_winapi' # <class '_frozen_importlib.BuiltinImporter'>
import 'ntpath' # <class '_frozen_importlib.FrozenImporter'>
import 'os' # <class '_frozen_importlib.FrozenImporter'>
import '_sitebuiltins' # <class '_frozen_importlib.FrozenImporter'>
Processing user site-packages
Processing global site-packages
Adding directory: 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312'
Adding directory: 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages'
Processing .pth file: 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\distutils-precedence.pth'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\site-packages\_distutils_hack\__pycache__\__init__.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\site-packages\_distutils_hack\__init__.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_distutils_hack\\__pycache__\\__init__.cpython-312.pyc'
import '_distutils_hack' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA306AB0>
Processing .pth file: 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pywin32.pth'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\site-packages\win32\lib\__pycache__\pywin32_bootstrap.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\site-packages\win32\lib\pywin32_bootstrap.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\win32\\lib\\__pycache__\\pywin32_bootstrap.cpython-312.pyc'
# possible namespace for C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\site-packages\pywin32_system32
import 'pywin32_system32' # <_frozen_importlib_external.NamespaceLoader object at 0x0000022DAA305610>
import 'pywin32_bootstrap' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3076E0>
Processing .pth file: 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\zope.interface-6.1-py3.12-nspkg.pth'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\types.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\types.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\types.cpython-312.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA33C590>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\importlib\__pycache__\__init__.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__pycache__\\__init__.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\warnings.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\warnings.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\warnings.cpython-312.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA33D2E0>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA33C3E0>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\importlib\__pycache__\_abc.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\importlib\_abc.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__pycache__\\_abc.cpython-312.pyc'
import 'importlib._abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA33E2A0>
import 'importlib.util' # <class '_frozen_importlib.FrozenImporter'>
import 'importlib.machinery' # <class '_frozen_importlib.FrozenImporter'>
# possible namespace for C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\site-packages\zope
import 'site' # <class '_frozen_importlib.FrozenImporter'>
# code object from C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\rlcompleter.py
# created 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\rlcompleter.cpython-312.pyc'
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\inspect.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\inspect.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\inspect.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\ast.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\ast.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\ast.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\__pycache__\__init__.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\__init__.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__pycache__\\__init__.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\enum.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\enum.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\enum.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\operator.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\operator.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\operator.cpython-312.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3A31A0>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\functools.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\functools.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\functools.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\collections\__pycache__\__init__.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\collections\__init__.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\collections\\__pycache__\\__init__.cpython-312.pyc'
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\keyword.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\keyword.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\keyword.cpython-312.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3EE120>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\reprlib.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\reprlib.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\reprlib.cpython-312.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3EE3F0>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3B10D0>
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3A3BC0>
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3A0620>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\__pycache__\_compiler.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\_compiler.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__pycache__\\_compiler.cpython-312.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\__pycache__\_parser.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__pycache__\\_parser.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\__pycache__\_constants.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\_constants.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__pycache__\\_constants.cpython-312.pyc'
import 're._constants' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA519790>
import 're._parser' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA518410>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\__pycache__\_casefix.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\re\_casefix.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__pycache__\\_casefix.cpython-312.pyc'
import 're._casefix' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA519850>
import 're._compiler' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3B28D0>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\copyreg.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\copyreg.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\copyreg.cpython-312.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA51AA20>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA38F950>
import '_ast' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\contextlib.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\contextlib.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\contextlib.cpython-312.pyc'
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA51B380>
import 'ast' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA37A4E0>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\dis.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\dis.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\dis.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\opcode.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\opcode.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\opcode.cpython-312.pyc'
import '_opcode' # <class '_frozen_importlib.BuiltinImporter'>
import 'opcode' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA54EE40>
import 'dis' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA37B620>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\collections\__pycache__\abc.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\collections\abc.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\collections\\__pycache__\\abc.cpython-312.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA5713D0>
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\linecache.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\linecache.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\linecache.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\tokenize.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\tokenize.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\tokenize.cpython-312.pyc'
# C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\__pycache__\token.cpython-312.pyc matches C:\Users\Fenius\AppData\Local\Programs\Python\Python312\Lib\token.py
# code object from 'C:\\Users\\Fenius\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\__pycache__\\token.cpython-312.pyc'
import 'token' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA573650>
import '_tokenize' # <class '_frozen_importlib.BuiltinImporter'>
import 'tokenize' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA571100>
import 'linecache' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA571340>
import 'inspect' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA359280>
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object at 0x0000022DAA3078F0>
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.


and python IS in PATH
![image](https://github.com/DamagingRose/Rose-Grabber/assets/87584186/8d6af125-3df0-4c8c-8d2d-635b3f1f7eb7)

**Comment by gumbobrot** [comment]
you need to type python -V

**Comment by gumbobrot** [comment]
also attach a screenshot of what happens when you run the builder

**Comment by Fenius64** [comment]
https://github.com/DamagingRose/Rose-Grabber/assets/87584186/ded19166-1f61-4067-9602-8fde79c1750e
well...here, this what happens and i get invalid escape sequence.

**Comment by Fenius64** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/87584186/854cf8d9-0800-4e48-82fa-69f49f890626)
this is what is in those lines that is causing this invalid sequence

**Comment by gumbobrot** [comment]
and you have python311 installed? and opened the builder over start.bat?

**Comment by Fenius64** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/87584186/e99aef3e-ad92-434a-833d-69448a705cf4)
yes i have python 311 installed and by opened the builder over start.bat do you mean drag builder.py to start.bat?

**Comment by gumbobrot** [comment]
uninstall all other versions pls

**Comment by gumbobrot** [comment]
amd copy all errors to raw messages here

**Comment by gumbobrot** [comment]
hello??

**Comment by Fenius64** [comment]
hello sorry i had school, but which version do i keep? python 3.11?

**Comment by gumbobrot** [comment]
311 yeah

**Comment by Fenius64** [comment]
ok so i uninstalled all python versions and opened the install.bat which installed python for me, when it did and the dependencies getting installed it gets stuck in nicegui install
![image](https://github.com/DamagingRose/Rose-Grabber/assets/87584186/44130c13-4025-4384-9ec8-19d5dda54ada)

**Comment by Fenius64** [comment]
nevermind! reopening the bat file fixed that

**Comment by Fenius64** [comment]
my issue has been fixed, thanks to the install.bat file, just uninstall all python versions you have, and open the install.bat, it should do everything for you

**Comment by Fenius64** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/87584186/d1aaa154-8cf9-40a8-b710-3232bf91018e)
help

**Comment by Fenius64** [comment]
it didnt send anything to the webhook but when u click test webhook it works

**Comment by gumbobrot** [comment]
> ok so i uninstalled all python versions and opened the install.bat which installed python for me, when it did and the dependencies getting installed it gets stuck in nicegui install
> ![image](https://github.com/DamagingRose/Rose-Grabber/assets/87584186/44130c13-4025-4384-9ec8-19d5dda54ada)
> 

it didn't, you randomly (i assume that happened accidently) selected something in the terminal, when you mark/highlight something in cmd the currently running process will pause, to fix this press esc once or simply restart the install.bat and make sure to **NOT** select something

**Comment by gumbobrot** [comment]
and by knowing that, i'm also sure that the other error you received was the result of you accidently highlithing something which caused the installation process to pause/break

**Comment by Fenius64** [comment]
do you have discord we can talk in? as the discord invite is not working currently, its much easier for this, and thank you ill try to run install.bat again

**Comment by gumbobrot** [comment]
> do you have discord we can talk in? as the discord invite is not working currently, its much easier for this, and thank you ill try to run install.bat again

`_gumbobrot`

**Comment by Fenius64** [comment]
friend request sent


also by the way uhh i got this now
![image](https://github.com/DamagingRose/Rose-Grabber/assets/87584186/f59bf5be-964b-4f35-b755-f7b94606e3d5)
it now is giving me this despite letting innstall.bat do its thing
also im so sorry about all of this, im really new to python and what not and i actually want to learn it
