### ISSUE TITLE
Where can I talk to you?

### ISSUE THREAD

**Issue by VarCharL** [DamagingRose/Rose-Grabber#145]
I have an inquiry I would like to talk to you about, so if you could give me your discord or telegram, it would be much appreciated, thanks

**Comment by UnofficialSlat** [comment]
Preferably a telegram, discord seems to get everyone perma banned lol

**Comment by gumbobrot** [comment]
> I have an inquiry I would like to talk to you about, so if you could give me your discord or telegram, it would be much appreciated, thanks

I'd like to receive your telegram.
