### ISSUE TITLE
still error

### ISSUE THREAD

**Issue by OlevO1** [DamagingRose/Rose-Grabber#146]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/95526844/c0c6679d-e36c-4607-aaca-5b99735a3c7f)
still error after the latest update

**Comment by gumbobrot** [comment]
`pip install pyinstaller --upgrade`

**Comment by OlevO1** [comment]
still not working 
![image](https://github.com/DamagingRose/Rose-Grabber/assets/95526844/7ac18a5c-950a-44f2-bb27-56ab92301261)

**Comment by OlevO1** [comment]
help me please

**Comment by gumbobrot** [comment]
dont use the System Information feature for now please

**Comment by OlevO1** [comment]
ok, now I turned it off and built it but still the same problem

**Comment by gumbobrot** [comment]
yuh, just wait for the fix and use another stealer at this time pls
