### ISSUE TITLE
dosent send to discord

### ISSUE THREAD

**Issue by memeesniff** [DamagingRose/Rose-Grabber#150]
i set it all up but when i test it it dosent send to discord

**Comment by gumbobrot** [comment]
bro how tf am i supposed to help when i dont get an error i can't magically figure out what's the problem

**Comment by memeesniff** [comment]
there is no error lmao

**Comment by gumbobrot** [comment]
so when you double clikc the final exe file nothing happens??

**Comment by something-0001** [comment]
Barring no further 'issues' (pun intended), this will be closed in 52 hours.

**Comment by gumbobr0t** [comment]
everything should be fixed now, make sure to try it and tell if it works fine for you now!
