### ISSUE TITLE
Error when Loading Up

### ISSUE THREAD

**Issue by buildman79** [DamagingRose/Rose-Grabber#152]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/135450417/935466dc-4ccb-457c-97ea-3aacb2cbc551)
When I installed, i opened the start.bat and it is stuck on the rose image. What do I do?

**Comment by gumbobrot** [comment]
check the cmd, if any errors occur they should be shown there  please ss it and if there are none, reopen the start.bat

**Comment by buildman79** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/135450417/0181ce7b-9f85-40aa-bcd1-df594d48b135)
It says this

**Comment by gumbobrot** [comment]
pip install --upgrade nicegui

**Comment by something-0001** [comment]
Run the command @gumbobrot mentioned in the reply inside of command prompt

**Comment by something-0001** [comment]
Barring no further 'issues' (pun intended), this will be closed in 52 hours.

**Comment by gumbobr0t** [comment]
i hope the latest release fixed everything, try it and pls tell us if it works for you
