### ISSUE TITLE
"ModuleNotFoundError: No module named 'nicegui' when running Rose-Grabber"

### ISSUE THREAD

**Issue by upsilun** [DamagingRose/Rose-Grabber#154]
When attempting to load the Rose-Grabber application, I encountered the following error message:

```powershell
Traceback (most recent call last):
  File "Rose-Grabber-main\components\roseui\builder.py", line 20, in <module>
    from nicegui import ui, app
ModuleNotFoundError: No module named 'nicegui'
```

I tried to fix the problem by installing
```
pip install nicegui
```

but it shows this message after installing 
```powershell
WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python311\\Scripts\\uvicorn.exe' -> 'C:\\Python311\\Scripts\\uvicorn.exe.deleteme'
```

**Comment by gumbobrot** [comment]
python installation corrupted or broken, uninstall all python versions, download python311 and make sure to tick the "Add to PATH" option, then try to run the install.bat and after it finished the start.bat

**Comment by something-0001** [comment]
If no further inquiries or questions are received regarding the bug or instructions in the previous reply; issue will be closed in 52 hours.
