### ISSUE TITLE
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by THE-ONLY-X** [DamagingRose/Rose-Grabber#155]
C:\Users\*****\AppData\Roaming\Python\Python311\site-packages\nicegui\nicegui.py:109: RuntimeWarning: coroutine 'AsyncServer.enter_room' was never awaited
  sio.enter_room(sid, client.id)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
![Uploading Screenshot (18).png…]()

**Comment by gumbobrot** [comment]
no ss attached, please try uninstalling nicegui and installing it back by running this command:
`pip uninstall nicegui && pip install nicegui`

**Comment by THE-ONLY-X** [comment]
is your dc termed?

**Comment by THE-ONLY-X** [comment]
![Screenshot (19)](https://github.com/DamagingRose/Rose-Grabber/assets/148107345/f38f44fb-538c-4a05-ad45-e49f13e794d8)

**Comment by THE-ONLY-X** [comment]
after reinstalling  nicegui

**Comment by THE-ONLY-X** [comment]
ama try to install on new window

**Comment by gumbobrot** [comment]
will look into it, just busy rn but working on a big update

**Comment by THE-ONLY-X** [comment]
uh

**Comment by THE-ONLY-X** [comment]
fix it please/

**Comment by gumbobrot** [comment]
`pip install --upgrade nicegui`

**Comment by THE-ONLY-X** [comment]
working ty also is ur old dc serv termed?

**Comment by gumbobrot** [comment]
yep, server termed

**Comment by something-0001** [comment]
> working ty also is ur old dc serv termed?

Good. Issue closed.
