### ISSUE TITLE
Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by misogynisticvicto** [DamagingRose/Rose-Grabber#156]
C:\Users\Victor\AppData\Roaming\Python\Python311\site-packages\nicegui\nicegui.py:109: RuntimeWarning: coroutine 'AsyncServer.enter_room' was never awaited
  sio.enter_room(sid, client.id)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
![image](https://github.com/DamagingRose/Rose-Grabber/assets/148112379/46b0bc35-54e8-4b81-b027-983be30362f2)

remembering that I already reinstalled nicegui, take a screenshot showing this.

**Comment by THE-ONLY-X** [comment]
nice wallpaper xD

**Comment by misogynisticvicto** [comment]
> nice wallpaper xD

thanks bro <3

**Comment by gumbobrot** [comment]
@misogynisticvicto

**Comment by something-0001** [comment]
Barring no further 'issues' (pun intended), this will be closed in 52 hours.

**Comment by gumbobr0t** [comment]
everything should be fixed, make sure to try it out, and if im allowed to ask, may i get your wallpaper sir??? look 🔥
