### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by something-0001** [DamagingRose/Rose-Grabber#158]
I apologize for not providing much information in regards to the template for a bug report.

That said; the bug(s) in question is two things. Once is the 69th line in sysinf.py, where the psutil.sensors_battery() function **_may_** return a NoneType value. This as a result errors out when non-laptops are tested on.

Secondly, after fixing the bug on my behalf, I noticed that the stub process repeatedly started itself over and over on process hacker. They always took up the same memory and CPU usage, meaning the process was just spawning itself but never dying.

I'm confident the latter is not caused from fixing the first issue. and If I can find why the process repeatedly starts itself over and over, I will submit a pull request fixing both bugs.

Edit-1 -- Could be because I'm on Python 3.12, where some wheels have not been built for the libraries.

**Comment by gumbobrot** [comment]
ay thanks, i will look into it, the wifi scanner may also return a nonetype obj i think i probably need to fix much stuff in the sysinfo. you'd really help me if you fixed these bugs and also the ransomware attribute stuff

**Comment by something-0001** [comment]
> ay thanks, i will look into it, the wifi scanner may also return a nonetype obj i think i probably need to fix much stuff in the sysinfo. you'd really help me if you supported me while fixing these bugs and also the ransomware attribute stuff

Once I can get the chance to fully do so later this evening, of course.
