### ISSUE TITLE
Private requests?

### ISSUE THREAD

**Issue by VarCharL** [DamagingRose/Rose-Grabber#160]
Hi, Do you do private requests for custom grabbers? if so lmk thanks

**Comment by xpierroz** [comment]
add xpierroz on discord

**Comment by gumbobrot** [comment]
> add xpierroz on discord 

you coding custom grabbers now?

**Comment by something-0001** [comment]
> Hi, Do you do private requests for custom grabbers? if so lmk thanks

Ask @gumbobr0t on telegram, his TG-contact and channel are provided in the README.md file.

**Comment by gumbobr0t** [comment]
> > Hi, Do you do private requests for custom grabbers? if so lmk thanks
> 
> Ask @gumbobr0t on telegram, his TG-contact and channel are provided in the README.md file.
> 
> I am not personally doing any custom grabbers, it seems @xpierroz is.

i also dont do any custom grabbers. maybe when i am a more skilled programmer.
