### ISSUE TITLE
rose not opening

### ISSUE THREAD

**Issue by rennoas** [DamagingRose/Rose-Grabber#166]
NiceGUI ready to go on http://127.0.0.1:8000
C:\Users\ariya\AppData\Roaming\Python\Python311\site-packages\nicegui\nicegui.py:109: RuntimeWarning: coroutine 'AsyncServer.enter_room' was never awaited
  sio.enter_room(sid, client.id) 
  i keep getting this error even tho i have the latest python and latest nicegui
  
  pls help

**Comment by gumbobr0t** [comment]
execute this cmd in the rose dir
`call myvenv\scripts\activate.bat && pip install --upgrade nicegui`

**Comment by gumbobr0t** [comment]
> NiceGUI ready to go on http://127.0.0.1:8000 C:\Users\ariya\AppData\Roaming\Python\Python311\site-packages\nicegui\nicegui.py:109: RuntimeWarning: coroutine 'AsyncServer.enter_room' was never awaited sio.enter_room(sid, client.id) i keep getting this error even tho i have the latest python and latest nicegui
> 
> pls help

we are using a virutal environment for our project, you'd need to install python version 3.11.5 and execute the command from the comment above

**Comment by rennoas** [comment]
by the way, how do i run on the rose directory?

**Comment by gumbobr0t** [comment]
Open the folder you wish to open the command prompt window from.

Type cmd into the location bar at the top of the window and tap enter.
https://www.lifewire.com/thmb/1BS2KRM3O17ENg8jbn8KuSQ0XyE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/how-to-open-command-prompt-in-a-folder-51855054-0699eed0772747c5ae3f803d57d4a0cc.jpg

Windows 10 folder with the search/location bar highlighted
The command prompt will now be opened in the desired location.

**Comment by gumbobr0t** [comment]
https://www.lifewire.com/open-command-prompt-in-a-folder-5185505

**Comment by rennoas** [comment]
i am on windows 11, the screenshot is in windows 10

**Comment by gumbobr0t** [comment]
yea its the same there

**Comment by rennoas** [comment]
it worked, tysm

**Comment by rennoas** [comment]
yall got a discord? send the link the one on the website doesnt work

**Comment by gumbobr0t** [comment]
> yall got a discord? send the link the one on the website doesnt work

we actively get termed :(

**Comment by gumbobr0t** [comment]
but we have a telegram
https://t.me/rosegrabber
