### ISSUE TITLE
The ordinal 380 could not be located in the dynamic link library  C:\Usersmobyl\Documents\Rose-Grabber-main\Rose.exe

### ISSUE THREAD

**Issue by moby-lovecraft** [DamagingRose/Rose-Grabber#171]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/145511810/2c25e258-7a2e-4ff1-8047-c5640413789b)

**Comment by gumbobr0t** [comment]
havent selected file icon, choose between standard exe and custom under icon, then rebuild

**Comment by moby-lovecraft** [comment]
worked thanks!!!

**Comment by gumbobr0t** [comment]
enjoy!
