### ISSUE TITLE
unhandled exception in script

### ISSUE THREAD

**Issue by listixx** [DamagingRose/Rose-Grabber#173]
help
![image](https://github.com/DamagingRose/Rose-Grabber/assets/149011110/74780693-603d-424c-8d76-6f4e53dea320)

**Comment by gumbobr0t** [comment]
install python 3.11.5 and uninstall all other versions, then run the build script again

**Comment by poncipp** [comment]
yo i updated the pip i run the builder.bat it ends without saying anythink just some words i have py 3.11.5

**Comment by gumbobr0t** [comment]
@something-0001 could you look into this?

**Comment by something-0001** [comment]
> help
> ![image](https://github.com/DamagingRose/Rose-Grabber/assets/149011110/74780693-603d-424c-8d76-6f4e53dea320)
> 

Hopefully you are using Python 3.11 to build this?

**Comment by something-0001** [comment]
> help
> ![image](https://github.com/DamagingRose/Rose-Grabber/assets/149011110/74780693-603d-424c-8d76-6f4e53dea320)
> 

Hopefully you are using Python 3.11 to build this?
