### ISSUE TITLE
runned the builder.bat it closed went to ui opened builder it crashed

### ISSUE THREAD

**Issue by poncipp** [DamagingRose/Rose-Grabber#174]
i have py 3.11
i updated pip to latest

**Comment by gumbobr0t** [comment]
i need the error

**Comment by gumbobr0t** [comment]
from the bat

**Comment by poncipp** [comment]
> from the bat

there's no error it just closes

**Comment by gumbobr0t** [comment]
there is, just call the batch file from the cmd

**Comment by poncipp** [comment]
![Capture](https://github.com/DamagingRose/Rose-Grabber/assets/149012254/624a69a8-e708-4d63-9cb8-d0340d3e7651)
last thing i see before it closed

**Comment by vabybatch** [comment]
its a logger

**Comment by poncipp** [comment]
> its a logger

might be the reason why it didnt open on vm

**Comment by gumbobr0t** [comment]
> its a logger

what? are you fckn stupid? its an open source project, learn coding before you talk skid

**Comment by gumbobr0t** [comment]
> > its a logger
> 
> might be the reason why it didnt open on vm

it clearly isnt a logger ur just stupid and couldnt wait for the requirements to install (or you marked something inside the cmd, that causes it to pause)

**Comment by gumbobr0t** [comment]
> its a logger

tell me where the logger is buddy

**Comment by poncipp** [comment]
> > > its a logger
> > 
> > 
> > might be the reason why it didnt open on vm
> 
> it clearly isnt a logger ur just stupid and couldnt wait for the requirements to install (or you marked something inside the cmd, that causes it to pause)

requirements do install the builder doesnt open

**Comment by gumbobr0t** [comment]
bro are you stupid? the builder.bat INSTALLS REQUIREMENTS AND OPENS THE BUILDER, i need an error

**Comment by poncipp** [comment]
> bro are you stupid? the builder.bat INSTALLS REQUIREMENTS AND OPENS THE BUILDER, i need an error

yes it installed the requriments but didn't open the builder

**Comment by gumbobr0t** [comment]
> ![Capture](https://github.com/DamagingRose/Rose-Grabber/assets/149012254/624a69a8-e708-4d63-9cb8-d0340d3e7651)
> last thing i see before it closed

when you're at this step it is still fckn installing

**Comment by gumbobr0t** [comment]
call the builder from a seperate cmd, then it will give error, show me

**Comment by something-0001** [comment]
> > > ![Capture](https://user-images.githubusercontent.com/149012254/278131070-624a69a8-e708-4d63-9cb8-d0340d3e7651.png)
> > > last thing i see before it closed
> > 
> > 
> > when you're at this step it is still fckn installing
> 
> well it closes i waited 10minute after it closed nothing happened

![image](https://github.com/DamagingRose/Rose-Grabber/assets/14898342/fcbe3ab7-0e8f-47ce-9aeb-da96c07a74f7)
![image](https://github.com/DamagingRose/Rose-Grabber/assets/14898342/9f60fde2-76d4-4f4f-9e79-52d900bb5d78)

Replicate this behavior, and show what error you get, if there are any.
