### ISSUE TITLE
When Rose UI Builder open it gives white screen

### ISSUE THREAD

**Issue by issam123xs** [DamagingRose/Rose-Grabber#175]
When Rose UI Builder open it gives white screen
![WHITE SCREEN](https://github.com/DamagingRose/Rose-Grabber/assets/79381848/2213d5ce-789b-4eb6-a25d-ff8f5399ddaf)

To Reproduce
1. when i run builder
2. cmd installed all the requireents
3. when the builder starts it gaves white screen

Expected behavior
When Rose UI Builder open it gives white screen

Desktop 
 - OS: [Windows 10 64 Bit]
 - Browser [Opera GX]

**Additional context**
The cmd complete and installed all the requirements but when the builder starts
it gave white screen

**Comment by gumbobr0t** [comment]
please send me the log file, also downgrade to python 3.11.5 and uninstall all other versions

**Comment by issam123xs** [comment]
> please send me the log file, also downgrade to python 3.11.5 and uninstall all other versions

ok but where do i find the logs

**Comment by issam123xs** [comment]
[roselog.log](https://github.com/DamagingRose/Rose-Grabber/files/13178103/roselog.log)

**Comment by issam123xs** [comment]
> please send me the log file, also downgrade to python 3.11.5 and uninstall all other versions

should i go to this link ? http://localhost:8000/home

**Comment by gumbobr0t** [comment]
no! as i said, downgrade to python 3.11.5 and uninstall all other versions.

**Comment by issam123xs** [comment]
> no! as i said, downgrade to python 3.11.5 and uninstall all other versions.

Okay i will uninstall al the version, wait for my reply

**Comment by gumbobr0t** [comment]
execute this in a cmd inside rose:
call myvenv/scripts/activate && pip install --upgrade nicegui

**Comment by issam123xs** [comment]
> execute this in a cmd inside rose: call myvenv/scripts/activate && pip install --upgrade nicegui

thx for the halp but the screen stays white, maybe i will use the grabber on the browser over here http://localhost:8000/home

**Comment by gumbobr0t** [comment]
yeah try

**Comment by gumbobr0t** [comment]
worked?

**Comment by issam123xs** [comment]
> worked?

yeh it works on the browser but it says connection lost trying to reconnect after a 10 minute of using
bruh idk where these probleme come from

**Comment by something-0001** [comment]
> > worked?
> 
> yeh it works on the browser but it says connection lost trying to reconnect after a 10 minute of using bruh idk where these probleme come from

The 10 minute thing may be a timeout of the local server. In any case, if it works out, that's good. This also means that this is resolved.
