### ISSUE TITLE
Webhook failed to execute 

### ISSUE THREAD

**Issue by saturbis1** [DamagingRose/Rose-Grabber#176]
This happens after pressing Test Webhook

![Screenshot 2023-10-27 153601](https://github.com/DamagingRose/Rose-Grabber/assets/149174612/fd91a8b2-c8fa-43de-a008-f027cef746a2)

**Comment by saturbis1** [comment]
My webhook is normal it looks like this https://discord.com/api/webhooks/1167460811745275905/xEugXoJtwgmuVXsX591KGGYVoaGYTTxLGvwAuvSh1qloGuinKSszO1EaMYwst2dLN7ow

**Comment by saturbis1** [comment]
is it on my site ? or can you fix it

**Comment by gumbobr0t** [comment]
Please check again if your webhook is correct. If you are sure it is a valid webhook, then there is only one possibility remaining: you have been ratelimited by the discord api. Please try again in a few minutes. You could also already build a stub and then test your sample on a virtual machine (OVM/VM). I recommend using [Triage](https://tria.ge). It is a high-quality online virtual machine. Another solution could be using a VPN or Proxy service to change your IP.

**Comment by saturbis1** [comment]
still not working ? is it because i do it from a virtual machine ?

**Comment by gumbobr0t** [comment]
Please make sure you have internet connection inside the VM.

**Comment by saturbis1** [comment]
yes im writing rn in it

**Comment by saturbis1** [comment]
what python version do i need ? and do i need to upgrade to the latest pip ? 
![Uploading Screenshot 2023-10-27 162733.png…]()

**Comment by gumbobr0t** [comment]
Probably ratelimited then...

**Comment by saturbis1** [comment]
but my webhook works for other ones

**Comment by saturbis1** [comment]
so how can i fix this

**Comment by gumbobr0t** [comment]
> what python version do i need ? and do i need to upgrade to the latest pip ? 
> ![Uploading Screenshot 2023-10-27 162733.png…]()
> 

Nope, you only need to have python 3.11.5 installed and launch the `builder.bat`.

**Comment by saturbis1** [comment]
yep im on python 3.11.5 and launched it

**Comment by gumbobr0t** [comment]
> but my webhook works for other ones
> 

You are ratelimited. If anyone else executes this it will probably work. Just not for you for some time.

**Comment by saturbis1** [comment]
yea but nothing will send to my webhook right ?

**Comment by saturbis1** [comment]
yesterday it didnt worked too

**Comment by gumbobr0t** [comment]
Any error when running the compiled executable?

**Comment by saturbis1** [comment]
should i do some settings or just test it

**Comment by gumbobr0t** [comment]
Please enable some stuff on the features tab. Also choose a build name, file icon and file type, enter a new webhook and press build. Then test that sample on https://tria.ge.

**Comment by saturbis1** [comment]
yo can you explain what Extension Spoofer is  ?

**Comment by saturbis1** [comment]
sorry im a newcomer
