### ISSUE TITLE
Exe to big

### ISSUE THREAD

**Issue by SeraphimI0** [DamagingRose/Rose-Grabber#177]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/140994615/edc07a4a-61ea-4ba5-9ebf-fae5eaf50e10)
the built exe is way to big even when I put it at 2 mb it comes out like that

**Comment by gumbobr0t** [comment]
Hi! The compiled stub has a static size of about 80-90MB because of the PyPi packages that are compiled into it. The file pumper **does not** set your file size to a specific amount, it **pumps** it. (Basically makes the output executable bigger.)

Have a good evening, Sir!

**Comment by gumbobr0t** [comment]
I don't really know why it comes out as 119MB tho, last time I tried I got 80MB. Must be an issue with the file pumping process calculation. Don't worry tho, we are working on a fud dropper. (Probably made in C++.)

**Comment by something-0001** [comment]
> I don't really know why it comes out as 119MB tho, last time I tried I got 80MB. Must be an issue with the file pumping process calculation. Don't worry tho, we are working on a fud dropper. (Probably made in C++.)

Make a C++ stealer lul.

**Comment by gumbobr0t** [comment]
> > I don't really know why it comes out as 119MB tho, last time I tried I got 80MB. Must be an issue with the file pumping process calculation. Don't worry tho, we are working on a fud dropper. (Probably made in C++.)
> 
> Make a C++ stealer lul.

nah too hard im learning nim & cpp rn but another stealer is more experienced
