### ISSUE TITLE
Webcam image stealer does not work

### ISSUE THREAD

**Issue by crealwithmilk** [DamagingRose/Rose-Grabber#180]
So basically, it says that my victim has one webcam but it doesn't send the picture

it also gave me this error on my discord server
Rose Instance - Error 
Error in Rose Webcam Stealer occurred | Help us by reporting this bug
float division by zero

**Comment by crealwithmilk** [comment]
turns out it was just a obs virtual cam 💀

**Comment by gumbobr0t** [comment]
> So basically, it says that my victim has one webcam but it doesn't send the picture
> 
> it also gave me this error on my discord server
> Rose Instance - Error 
> Error in Rose Webcam Stealer occurred | Help us by reporting this bug
> float division by zero

yes, im still looking for a fix (have been for weeks)but couldnt find anything, is an issue with the pygame library
