### ISSUE TITLE
Hooked a random

### ISSUE THREAD

**Issue by sigmajas** [DamagingRose/Rose-Grabber#181]
Hey,
I have hooked somebody that I haven't even sent the file. It's a bit weird because some of the results Seen wrong and it's somebody from an other continent.

**Comment by Doubleoffline** [comment]
it can be bots

**Comment by gumbobr0t** [comment]
> Hey,
> I have hooked somebody that I haven't even sent the file. It's a bit weird because some of the results Seen wrong and it's somebody from an other continent. 

enabled antivm? they are probably vms

**Comment by Doubleoffline** [comment]
> > Hey,
> > I have hooked somebody that I haven't even sent the file. It's a bit weird because some of the results Seen wrong and it's somebody from an other continent.
> 
> enabled antivm? they are probably vms

i added u on dc

**Comment by sigmajas** [comment]
OK thanks

**Comment by gumbobr0t** [comment]
> OK thanks,
> but still can it possibly be a vm because the grabber also took a screenshot.

you shouldnt get vms with antivm enabled, please provide the ss so i can tell if it's a vm or not

**Comment by sigmajas** [comment]
![screenshot](https://github.com/DamagingRose/Rose-Grabber/assets/119691100/318bf5e7-6129-4d2c-8846-0868f929616c)

**Comment by sigmajas** [comment]
That's the Screenshot. If you want I can also give you the grabber results. The aren't any passwords so I also think it's just a bot thank you guys.

**Comment by gumbobr0t** [comment]
yeah thats defenitely a vm

**Comment by gumbobr0t** [comment]
it would be good if you sent me the devices data like hwid, Mac, ip, User etc

**Comment by gumbobr0t** [comment]
its a malware Scanner from Services like virustotal (Probably a sandbox) or just a microsoft or Google virus Scanner

**Comment by gumbobr0t** [comment]
> HWID: 11111111-2222-3333-4444-555555555555
> Internal IP: 192.168.0.98
> External IP: 20.114.22.115
> Mac: 05:17:5D:75:D5:54
> RAM: 1GB
> 
> Yeah must be a VM because 2 internal and external IP
> and 1 GB RAM 💀
> 
> You are all saying that's a VM (I think you mean Virtual Machines) but does that mean it's a bot or a VM from a person 

whats about the device username and hostname?

**Comment by sigmajas** [comment]
Host Name: DORREYES
Username: joshuarob

**Comment by gumbobr0t** [comment]
ty! i think i can close this now

**Comment by gumbobr0t** [comment]
oh nvm i'll leave it opened to remind myself to add the names, ips, macs, hwids etc to the blacklist

**Comment by sigmajas** [comment]
I have to thank you

**Comment by something-0001** [comment]
> HWID: 11111111-2222-3333-4444-555555555555 Internal IP: 192.168.0.98 External IP: 20.114.22.115 Mac: 05:17:5D:75:D5:54 RAM: 1GB
> 
> Yeah must be a VM because 2 internal and external IP and 1 GB RAM 💀
> 
> You are all saying that's a VM (I think you mean Virtual Machines) but does that mean it's a bot or a VM from a person

Unless multiple are required to be added, I will go ahead and add these.
