### ISSUE TITLE
How do I remove this tool from my system?

### ISSUE THREAD

**Issue by Toyv2** [DamagingRose/Rose-Grabber#183]
oh no! i ran the file on my own device and the startup still persists?? why are all my security sites blocked tho? and why are most of my files name `.doggo.encrypted` ...? please help.

**how do i remove this software from my device?**

**Comment by gumbobr0t** [comment]
Hi! So first you need to delete this directory:
1. Enter the appdata dir through pressing Windows + R and writing `%APPDATA%`.
2. Find the directory `rose` & delete it.

And then the reg entry:
1. Enter the regedit by pressing Windows + R and then put in `regedit`.
2. At the top path write down this: `HKCU/Software/Microsoft/Windows/CurrentVersion/Run`.
3. On the right side you should see the reg entry `rose`. Right click it and press delete.

I hope this works for you. If you have chosen to Block sites or encrypt your files over the ransomware, please Look into the resources/util folder. There you'll find some files to revert these things.

**Comment by gumbobr0t** [comment]
Enjoy your day!
