### ISSUE TITLE
Test Webhook works fine. but not in the build

### ISSUE THREAD

**Issue by dumbex6** [DamagingRose/Rose-Grabber#185]
![Capture](https://github.com/DamagingRose/Rose-Grabber/assets/78320163/fe55f314-a89d-4f70-94db-8017ad0da488)
![Capture](https://github.com/DamagingRose/Rose-Grabber/assets/78320163/3babd199-16d2-4c38-acb5-1c5927f44b32)

**Comment by gumbobr0t** [comment]
Hi! Please provide your webhook.
