### ISSUE TITLE
Test Webhook not showing: "connected", only show blank text?

### ISSUE THREAD

**Issue by jschaeferking** [DamagingRose/Rose-Grabber#187]
Test Webhook not showing: "connected", only show blank text?

![image](https://github.com/DamagingRose/Rose-Grabber/assets/25907221/9f82b817-fd61-4618-897e-b70f505929b3)

Check screenshot for more.

**Comment by gumbobr0t** [comment]
we are already chatting over discord, so i think i can close this! lets continue there.
