### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by VarCharL** [DamagingRose/Rose-Grabber#189]
Hey, a cool idea would maybe be sending all user data to a telegram bot so you do not get your ass fucked by discord.

**Comment by gumbobr0t** [comment]
thanks for the idea

**Comment by gumbobr0t** [comment]
smth, dont close, i need this as reminder, might consider switching, discord be wildin these days, their terms go brrrr

**Comment by something-0001** [comment]
> smth, dont close, i need this as reminder, might consider switching, discord be wildin these days, their terms go brrrr

Didn't plan on closing.

**Comment by gumbobr0t** [comment]
oki goodd

**Comment by zen1em** [comment]
> oki goodd

is ur hole pink

**Comment by gumbobr0t** [comment]
black

**Comment by gumbobr0t** [comment]
v2 will have telegram integration in later releases probably. join discord https://dsc.gg/rose-stealer
