### ISSUE TITLE
I got someone to download and run it but it never sent the stuff to my webhook

### ISSUE THREAD

**Issue by frostoffpercs** [DamagingRose/Rose-Grabber#191]
so i recently made a cookie logger using your ui and tested my webhook and everything but it never sent the info and files and cookies

**Comment by gumbobr0t** [comment]
hi! please make sure you've enabled stuff on the features side, please also provide errors if you see any and i'll need the log file (roselog.log)

**Comment by something-0001** [comment]
> so i recently made a cookie logger using your ui and tested my webhook and everything but it never sent the info and files and cookies

If you can upload the roselog.log file to gofile, and then send the link here, that would be great.

Without it, issues cannot be resolved. Please do so within 96 hours, it'll be closed by then without a file.
