### ISSUE TITLE
Where can i see rose and knight rat commands/features?

### ISSUE THREAD

**Issue by Suxirda** [DamagingRose/Rose-Grabber#192]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gumbobr0t** [comment]
bugged right now, dont use rats

**Comment by something-0001** [comment]
RAT is bugged, do not use until it is fixed. For reference, a commit fixing the RAT will have the issue embedded in it's description.
