### ISSUE TITLE
I got error dhooks not collected

### ISSUE THREAD

**Issue by silyaX** [DamagingRose/Rose-Grabber#194]
I got error dhooks not collected

**Comment by gumbobr0t** [comment]
blawg speak proper english or provide a ss of the err

**Comment by zen1em** [comment]
> blawg speak proper english or provide a ss of the err

to be fair i seen the error too what is it

**Comment by gumbobr0t** [comment]
bro i dont need to know whos seen it or what it does i need the exact plain text error

**Comment by something-0001** [comment]
Pending has been added to the issue.

This means you have 96 hours to upload the log (`roselog.log`) file to here or another form of media (thereby sending the link here.)

It will be closed without a file provided.
