### ISSUE TITLE
How to update pip to new relase

### ISSUE THREAD

**Issue by JulkaXO** [DamagingRose/Rose-Grabber#196]
Hello I have a problem with the pip update, I can't install it. I looked at other reports but they didn't help. Below is a screanshot
![Zrzut ekranu (7)](https://github.com/DamagingRose/Rose-Grabber/assets/149944273/ed8ea87f-bf97-4747-a23b-1200604a3739)

**Comment by gumbobr0t** [comment]
> Hello I have a problem with the pip update, I can't install it. I looked at other reports but they didn't help. Below is a screanshot
> ![Zrzut ekranu (7)](https://github.com/DamagingRose/Rose-Grabber/assets/149944273/ed8ea87f-bf97-4747-a23b-1200604a3739)
> 

No worries, it is installing. It has nothing to do with pip. It just needs some time because its installing many many packages. So lave it open and wait until it finished.

**Comment by gumbobr0t** [comment]
Depending on your ibternet and system it can take up to 10 minutes i would say.

**Comment by something-0001** [comment]
The issue has been closed.

Upgrading pip can be done via `py -m pip install --upgrade pip` in an **administrator** shell, or command prompt.
![image](https://github.com/DamagingRose/Rose-Grabber/assets/14898342/9b7f6be8-0020-493a-b943-9f917956735c)
