### ISSUE TITLE
Windows Defender Detecting Rose

### ISSUE THREAD

**Issue by georgie-dev** [DamagingRose/Rose-Grabber#197]
Windows Defender keeps detecting and deleting the file

**Comment by gumbobr0t** [comment]
yeah and what im i supposed to do?? it got 6 detections on virustotal without anti-vm, anti-debug and obfuscation which is pretty decent. just buy a crypter buddy

**Comment by x00xies** [comment]
Can you direct to a good crypter that can do the magic?

**Comment by gumbobr0t** [comment]
> Can you direct to a good crypter that can do the magic?

no

**Comment by something-0001** [comment]
Right now, the grabber isn't designed to be fully undetected. There is essentially no obfuscation, and, the file has been tested on many platforms like VT and any.run.

WD of course picks up on this. I'll see if there are any offending strings that can be changed to make scantime detections go down.
