### ISSUE TITLE
Confusing typo?

### ISSUE THREAD

**Issue by cyberhy** [DamagingRose/Rose-Grabber#199]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/147515189/c2515223-09fb-4596-9d1b-d10a579e1807)

**Comment by gumbobr0t** [comment]
ooops, yea however its not working atm so dont use, will fix when i have time

**Comment by something-0001** [comment]
The typo will be fixed when I get the chance.

**Comment by something-0001** [comment]
This is resolved. Download the new builder, it should be fixed.
