### ISSUE TITLE
Problem with pip and builder wheel when run the builder

### ISSUE THREAD

**Issue by Zachtryingforuser** [DamagingRose/Rose-Grabber#202]
I downgraded to python 3.11.1 bc it told me to downgrade to  python 11 then it said that there was a problem with the pip or something like that

**Comment by Zachtryingforuser** [comment]
https://pillow.readthedocs.io/en/latest/installation.html
it showed me this

**Comment by Zachtryingforuser** [comment]
[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
Failed to build Pillow httptools
ERROR: Could not build wheels for Pillow, httptools, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by something-0001** [comment]
Have you uninstalled Python 3.12?

**Comment by Zachtryingforuser** [comment]
Yeah i did

**Comment by something-0001** [comment]
Try `py -m pip install --only-binary Pillow Pillow` and `py -m pip install --only-binary httptools httptools`

**Comment by gumbobr0t** [comment]
he needs to exec the cmd properly inside the venv

**Comment by gumbobr0t** [comment]
@Zachtryingforuser still issues or nah?

**Comment by gumbobr0t** [comment]
> he needs to exec the cmd properly inside the venv

if u dont understand this, msg my discord, i put it on this github profile
