### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by zen1em** [DamagingRose/Rose-Grabber#203]
when i test the stub for myself i get this error

![image](https://github.com/DamagingRose/Rose-Grabber/assets/139626365/ef9bb5db-04d2-4712-9e9c-1b3ea8b787ba)

if anybody could help that would be great

**Comment by gumbobr0t** [comment]
you havent selected an icon for the executable. you need to specify the file type and file icon.

**Comment by zen1em** [comment]
> you havent selected an icon for the executable. you need to specify the file type and file icon.

oh ty
