### ISSUE TITLE
Getting an error that it cant grab passwords

### ISSUE THREAD

**Issue by iiMAtEAs** [DamagingRose/Rose-Grabber#204]
Traceback (most recent call last):
  File "main.py", line 61, in <module>
  File "getpass.py", line 168, in getuser
ModuleNotFoundError: No module named 'pwd'

**Comment by iiMAtEAs** [comment]
dont know how to fix it

**Comment by ozcanpng** [comment]
same problem...

**Comment by something-0001** [comment]
Will look into it.

**Comment by something-0001** [comment]
Closed, should work with the new main.py file.
