### ISSUE TITLE
not makeing the .exe file

### ISSUE THREAD

**Issue by Razberiwaffl** [DamagingRose/Rose-Grabber#207]
**Describe the bug**
so im makeing my thing and i click open folder and

![image](https://github.com/DamagingRose/Rose-Grabber/assets/142365053/b7fef16a-2909-4752-a02d-dbfd8f56d6af)
 nothing is shown from my knowledge and i was wondering if there was a spot here the thing goes

**Comment by something-0001** [comment]
Send the roselog.log file found in the folder you took a screenshot of.

**Comment by Razberiwaffl** [comment]
i cant anymore bc i made one with like nothing and it now wont stop working and wont let my into anything
so it would be great if i could get how to get rid of it

**Comment by something-0001** [comment]
> i cant anymore bc i made one with like nothing and it now wont stop working and wont let my into anything
> so it would be great if i could get how to get rid of it 
> 

If you want to get rid of this, then you can simply delete the folder.

**Comment by Razberiwaffl** [comment]
ok thank you ima re download it and i do think i got it now tho sorry for waisting your time thank you
