### ISSUE TITLE
tell people how to disable it off your own divice

### ISSUE THREAD

**Issue by Razberiwaffl** [DamagingRose/Rose-Grabber#209]
all the other token grabbers and all that i can safly test it on myself but i cant with this and now i would love to know it there is something to get rid of this

**Comment by something-0001** [comment]
Ask others. This is not the place to discuss it.

**Comment by gumbobr0t** [comment]
lil bro we already have an issue pinned that shows how to remove rose

https://github.com/DamagingRose/Rose-Grabber/issues/183

**Comment by gumbobr0t** [comment]
@Razberiwaffl
