### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ArjixWasTaken** [DamagingRose/Rose-Grabber#210]
I just have one question for people like you that make malware publicly available "for educational reasons".
Why?

We clearly know that "educational research" is just an excuse.
Credential stealers ain't hard to make, how much are you really learning from this other than basic programming concepts?

Let's not pretend that these are not used in the wild, of course they are.
You are making it easier for malicious actors to do damage on others.

Yes, one may say that there are countless token stealers, that this is just a drop in the water, but that is just avoiding the subject.
If nobody made malware publicly available, then less people would have access to it, so what's the deal with you?

I know my thoughts are naive, but I can't see any justification to this.
Please do enlighten me.

**Comment by something-0001** [comment]
Rose, I'm guessing is a test repository for the owner's new project, which has been discussed on his Telegram.

That said, I just picked up on improving the code a little a few weeks ago, with no prior involvement. You can ask him directly on his Telegram, but, the issues side of any repository are for legitimate questions regarding the functionality of the code, not just questioning intended purposes.

Essentially, the wrong place to ask. Hope you find luck with the aforementioned solution!

Good day!

**Comment by something-0001** [comment]
Rose, I'm guessing is a test repository for the owner's new project, which has been discussed on his Telegram.

That said, I just picked up on improving the code a little a few weeks ago, with no prior involvement. You can ask him directly on his Telegram, but, the issues side of any repository are for legitimate questions regarding the functionality of the code, not just questioning intended purposes.

Essentially, the wrong place to ask. Hope you find luck with the aforementioned solution!

Good day!

**Comment by something-0001** [comment]
To add on, if you feel this is truly detrimental to the public, report the repository on your own will.

**Comment by ArjixWasTaken** [comment]
> To add on, if you feel this is truly detrimental to the public, report the repository on your own will.

I did not report this repository because GitHub is known as a place where open source malware is accepted.

**Comment by ArjixWasTaken** [comment]
> Essentially, the wrong place to ask. Hope you find luck with the aforementioned solution!

I mean, as a project meant for "educational research" I'd assume questions are not off-limits, it's not as if this project was intended to be used outside of educational purposes, right?

Ofc I don't believe that latter part, but it is what the README claims.
