### ISSUE TITLE
Ransomware Error 

### ISSUE THREAD

**Issue by githubianuser** [DamagingRose/Rose-Grabber#212]
when someone runs everything works and sends normally expect the ransomware, it gives me this error. 

Rose Report
Rose Instance - Error
Error in Doggo Ransomware occured | Help us by reporting this bug
"cannot access local variable 'key' where it is not associated with a value"

**Comment by something-0001** [comment]
Ransomware is bugged. This will be fixed later.

**Comment by gumbobr0t** [comment]
fixed @githubianuser
