### ISSUE TITLE
A discord server

### ISSUE THREAD

**Issue by rwaul** [DamagingRose/Rose-Grabber#214]
You guys should make a discord server so people can ask for help and support. The server chat can be nuked every 1 day so the server doesn't get termed. Also you guys can use terms like reet/r4t instead of rat so it doesn't get termed because of malicious intentions. If you guys have a discord server already please invite me in it

**Comment by rwaul** [comment]
or if someone can drop his discord here, cause i want to talk with him something.

**Comment by gumbobr0t** [comment]
> You guys should make a discord server so people can ask for help and support. The server chat can be nuked every 1 day so the server doesn't get termed. Also you guys can use terms like reet/r4t instead of rat so it doesn't get termed because of malicious intentions. If you guys have a discord server already please invite me in it
> 

no time for handling a server, helping people or making sure it doesnt get termed

**Comment by gumbobr0t** [comment]
> or if someone can drop his discord here, cause i want to talk with him something.
> 

look at my profile, my discord is there

**Comment by rwaul** [comment]
> > You guys should make a discord server so people can ask for help and support. The server chat can be nuked every 1 day so the server doesn't get termed. Also you guys can use terms like reet/r4t instead of rat so it doesn't get termed because of malicious intentions. If you guys have a discord server already please invite me in it
> 
> no time for handling a server, helping people or making sure it doesnt get termed

i can help you guys with it, i've been managing couple of servers including mine that i succeed to get at 3k members and couple more.
