### ISSUE TITLE
Revert Previous Changes to sysinf.py

### ISSUE THREAD

**Issue by something-0001** [DamagingRose/Rose-Grabber#217]
The syntax itself is incorrect, so it's not included in the build, therefore being screwed out and killing the stub.

**Comment by something-0001** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/14898342/fa3db13b-a5ec-4a49-ac41-52f39d08d131)

**Comment by gumbobr0t** [comment]
hahahaha sorry yes o did it fast on mobile i'll do it when im home

**Comment by gumbobr0t** [comment]
done, sorry, do you still have rights to commit? and whats about your new discord account? @something-0001

**Comment by something-0001** [comment]
> done, sorry, do you still have rights to commit? and whats about your new discord account? @something-0001 

Already sent the new one in Telegram. Perms are still here but I was on mobile at the time

**Comment by gumbobr0t** [comment]
ah okay, btw i havent received anythin on tg?
