### ISSUE TITLE
who do it have 20 detects and in the old version it had 10 ?

### ISSUE THREAD

**Issue by KingSoreeee** [DamagingRose/Rose-Grabber#223]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gumbobr0t** [comment]
its really depending on the features you choose. if you want a fud stealer, we recommend you, wait for rosev2

**Comment by gumbobr0t** [comment]
also, rose is slightly getting bigger, so also getting registered to virus banks, but i am rewriting the main part of the actual stealer right now, so they might go down soon.

**Comment by gumbobr0t** [comment]
probably because of the xmr miner the detections raise
