### ISSUE TITLE
Hello, can you add other crypto payment options in the RW/Miner?

### ISSUE THREAD

**Issue by githubianuser** [DamagingRose/Rose-Grabber#228]
Hello, can you add other crypto payment options in the RW/Miner?

Would you be able to add other payment options for the victim and have them pay in something like LTC instead of monero? 

Also when you adding Telegram as a C2

**Comment by gumbobr0t** [comment]
as of my knowledge, xmrig is the easiest for background setup and is pretty efficient, also im currently working on rosev2. v1 is discontinued
