### ISSUE TITLE
builder error

### ISSUE THREAD

**Issue by githubianuser** [DamagingRose/Rose-Grabber#229]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by githubianuser** [comment]
it just says "Internal Servor Error"

**Comment by whoishype01** [comment]
same for  me

**Comment by gumbobr0t** [comment]
download new version

**Comment by gumbobr0t** [comment]
@whoishype01 @githubianuser

**Comment by githubianuser** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/151575372/94986fe3-9f6a-46ed-809d-bfbe49b38594)

**Comment by githubianuser** [comment]
getting this error when executing the stub

**Comment by gumbobr0t** [comment]
i need the full error in plaintext and both log files.

**Comment by githubianuser** [comment]
Fixed that, it was because it was ran as admin. but Now I get this error for the RW 
![image](https://github.com/DamagingRose/Rose-Grabber/assets/151575372/a12986fb-55a8-48d7-a6b0-106d5284e8e8)

**Comment by gumbobr0t** [comment]
yeah ransomware doesnt work. wait for the new v2. https://dsc.gg/rosestealer
