### ISSUE TITLE
I cannot create a exe file it only creates a py file

### ISSUE THREAD

**Issue by adgwfg** [DamagingRose/Rose-Grabber#231]
Removing MetaData
Traceback (most recent call last):
  File "C:\Users\adios\Downloads\Rose-Grabber\resources\utils\comp\post.py", line 37, in <module>
    RemoveMetaData(builtFile)
  File "C:\Users\gansa\Downloads\Rose-Grabber\resources\utils\comp\post.py", line 6, in RemoveMetaData
    with open(path, "rb") as file:
         ^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'dist\\Built.exe'
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: Build.exe: FileNotFoundException: Build.exe: No such file or directory

Packed 0 files.

I cannot create a exe file it only creates a py file

**Comment by gumbobr0t** [comment]
join discord here: https://dsc.gg/rosestealer and follow instructions on support channel after verifying.
