### ISSUE TITLE
starting builder, press any key to continue but then nothing happens

### ISSUE THREAD

**Issue by HYPERDYNAMYX** [DamagingRose/Rose-Grabber#232]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/149238655/d3bde64e-ad01-42c1-bd9f-4a412320b70b)
when i press a key to continue, gui doesn't load up

**Comment by Th3Fr0st** [comment]
me to
any error up?

**Comment by gumbobr0t** [comment]
download new version and try again. this is discontinued anyways. join discord for v2
dsc.gg/rosestealer

**Comment by Moonjifly** [comment]
can u update the inv link? @gumbobrot
